version: '3'
services:
  payara:
    build:
      context: ./images/payara/
      args:
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOSTNAME=${DB_HOSTNAME}
        - DB_PORT=${DB_PORT}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - HOST_NAME=${HOST_NAME}
        - HOST_USER=${HOST_USER}
    ports:
      - "8080:8080"
      - "4848:4848"
    links:
      - mysql:db
  mysql:
    build:
      context: ./images/mysql/
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  phpmyadmin:
    build:
      context: ./images/phpmyadmin/
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "6060:80"
    links:
      - mysql:db
